### ISSUE TITLE
graph widgets available?

### ISSUE THREAD

**Issue by GeorgeGkinis** [charmbracelet/bubbles#317] opened 2023-01-27 00:42 UTC
Feature request.

I was considering things like pie chart, line chart, barplot etc..
Like [termui](https://github.com/gizak/termui) has

It would look fantastic!

**Comment by Morphclue** [comment] 2023-02-13 14:01
This seems to be a duplicate of #241.

**Comment by bashbunni** [comment] 2023-02-15 21:10
This is a duplicate. I'm going to close it, so we can keep the conversation in one place. 😄

**Closed by bashbunni** 2023-02-15 21:10 UTC
