### ISSUE TITLE
Softwrap

### ISSUE THREAD

**Issue by dajohi** [charmbracelet/bubbles#222] opened 2022-08-21 16:50 UTC
Is it possible to do softwrap on a viewport, where the line is word-wrapped on the display, but the actual text is not altered with newlines?

**Comment by knz** [comment] 2022-09-03 13:35
@dajohi you can use textarea for this.

**Comment by muesli** [comment] 2022-10-05 04:33
@knz While you're right, if I understand it correctly @dajohi refers to a read-only view.

Closing as a dupe of #56.

**Closed by muesli** 2022-10-05 04:33 UTC
Labels: duplicate
